Docs: Add integration docs and some developer docs
bottlerocket-os/bottlerocket-ecs-updater pull request #115
Opened 2023-06-12 16:51 UTC by jpmcb

**Issue number:**

N/a

**Description of changes:**

Adds some missing integration docs and developer docs.

**Testing done:**

N/a

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2023-06-12 18:01 UTC, stmcginnis requested changes

2023-06-12 18:01 UTC, stmcginnis commented on integ/README.md
> +This will setup an ECS cluster using the integration cloud formation stack
nit: s/cloud formation/CloudFormation/

2023-06-12 18:01 UTC, stmcginnis commented on integ/README.md
> +It’s also similar to how the ECS updater MCM works, so it’s useful to go through it and should in total take less than 1 hour.
What's the "ECS updater MCM"?

2023-06-12 18:01 UTC, stmcginnis commented on integ/README.md
> +1. You’ll want to set up a test ECS cluster.
There should be a blank line after this initial bullet item line, then all content part of 1 should be indented three spaces to make sure it gets formatted properly as item content when rendered.

2023-06-12 18:01 UTC, stmcginnis commented on integ/README.md
> +```
Same not on indentation, for all following bullet items.

2023-06-12 20:16 UTC, webern approved these changes

2023-06-12 20:16 UTC, webern commented on integ/README.md
> +It’s also similar to how the ECS updater MCM works, so it’s useful to go through it and should in total take less than 1 hour.
Maybe 
```suggestion
It’s also similar to how we publish the ECS updates, so it’s useful to go through it and should in total take less than 1 hour.
```

2023-06-12 21:36 UTC, stmcginnis approved these changes
Thanks!

2023-06-14 15:30 UTC, arnaldo2792 approved these changes

2023-06-14 15:49 UTC, merged